name: Maven Package and Deploy

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Extract artifact details
        id: extract
        run: |
          echo "::set-output name=ARTIFACT_ID::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)"
          echo "::set-output name=VERSION::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install paramiko
        run: |
          python -m pip install --upgrade pip
          pip install paramiko

      - name: Delete file from SFTP
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          ARTIFACT_ID: ${{ steps.extract.outputs.ARTIFACT_ID }}
        run: |
          python delete-file-from-sftp.py

      - name: Upload to SFTP server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          local_path: 'target/${{ steps.extract.outputs.ARTIFACT_ID }}-${{ steps.extract.outputs.VERSION }}.jar'
          remote_path: '/plugins/'
          sftp_only: true